1. Install Library

In [3]:
!pip install google-play-scraper
!pip install pandas
!pip install openpyxl

Requirement already satisfied: google-play-scraper in /usr/local/lib/python3.12/dist-packages (1.2.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

2. Import Library

In [4]:
import pandas as pd
from google_play_scraper import reviews, Sort

3. Menentukan Aplikasi

In [5]:
app_id = "com.ocbcnisp.onemobileapp"

4. Melakukan Scraping

In [6]:
result, continuation_token = reviews(
    app_id,
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=15000
)

5. Cek Jumlah Review

In [7]:
print("Jumlah Review :", len(result))

Jumlah Review : 15000

6. Membuat DataFrame

In [8]:
data = []

for review in result:

    data.append({

        'Username': review['userName'],
        'Review': review['content'],
        'Rating': review['score'],
        'Tanggal': review['at']

    })

df = pd.DataFrame(data)

7. Melihat Dataset

In [9]:
df.head()

,Username,Review,Rating,Tanggal
0,Pengguna Google,"sangat puas dengan pelayanan keluhan nya,uang ...",5,2026-07-11 08:14:27
1,Pengguna Google,saya ingin bertanya berapa hari kartu debit ny...,3,2026-07-10 06:58:34
2,Pengguna Google,kenapa mbanking saya tidak bisa melakukan tran...,4,2026-07-10 02:22:07
3,Pengguna Google,siap 👍,5,2026-07-09 01:39:14
4,Pengguna Google,Sistem pelayanan dan M-banking nya sangat kura...,1,2026-07-08 14:10:27

8. Informasi Dataset

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Username  15000 non-null  object
 1   Review    15000 non-null  object
 2   Rating    15000 non-null  int64
 3   Tanggal   15000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 468.9+ KB

9. Statistik Rating

In [11]:
df.describe()

             Rating                        Tanggal
count  15000.000000                          15000
mean       3.196533  2022-07-28 17:06:08.277733376
min        1.000000            2020-07-19 16:16:57
25%        1.000000  2021-04-20 01:16:54.750000128
50%        4.000000            2021-11-14 03:39:58
75%        5.000000            2023-08-09 21:30:18
max        5.000000            2026-07-11 08:14:27
std        1.817910                            NaN

10. Cek Missing Value

In [12]:
df.isnull().sum()

Username    0
Review      0
Rating      0
Tanggal     0
dtype: int64

11. Menghapus Data Kosong

In [13]:
df = df.dropna()

12. Menghapus Review Duplikat

In [14]:
df = df.drop_duplicates(subset=['Review'])

13. Simpan Dataset

In [15]:
df.to_csv(
    "hasil_scraping_OCBC.csv",
    index=False,
    encoding="utf-8-sig"
)

14. Download Dataset (Google Colab)

In [16]:
from google.colab import files
files.download("hasil_scraping_OCBC.csv")

15. Menampilkan 10 Review Pertama

In [17]:
df.head(10)

,Username,Review,Rating,Tanggal
0,Pengguna Google,"sangat puas dengan pelayanan keluhan nya,uang ...",5,2026-07-11 08:14:27
1,Pengguna Google,saya ingin bertanya berapa hari kartu debit ny...,3,2026-07-10 06:58:34
2,Pengguna Google,kenapa mbanking saya tidak bisa melakukan tran...,4,2026-07-10 02:22:07
3,Pengguna Google,siap 👍,5,2026-07-09 01:39:14
4,Pengguna Google,Sistem pelayanan dan M-banking nya sangat kura...,1,2026-07-08 14:10:27
5,Pengguna Google,OCBC kenapa gak bisa unduh E-statement? Tiap d...,2,2026-07-08 12:45:48
6,Pengguna Google,saya kasih bintang 5 biar ada respon...saya mi...,5,2026-07-08 12:34:03
7,Pengguna Google,ape yaaa gak sesuai,1,2026-07-08 07:41:44
8,Pengguna Google,proses activasi masih butuh uang rekomendasi n...,2,2026-07-07 19:31:27
9,Pengguna Google,pendaftaran paling ribet yang pernah saya daftar,1,2026-07-07 07:54:30

16. Menampilkan 10 Review Terakhir

In [18]:
df.tail(10)

,Username,Review,Rating,Tanggal
14988,Saepul Akso,Aplikasi ga guna kata nya lebih mudah di rumah...,1,2020-07-21 02:00:10
14989,Erick Depot,Luar biassa,5,2020-07-21 00:35:00
14990,Dika Ican,sumpah parah loading lama banget njir setelah ...,1,2020-07-20 18:01:08
14991,Hendrik Travolta,Selamat menikmatin layanan ini,5,2020-07-20 16:29:10
14992,Naila Nur Fatihah,Aplikasi yg sangat buruk jauh dengan aplikasi ...,1,2020-07-20 14:09:22
14994,Dewita Sy,Tolong di perbaiki lagi kenapa kendalanya mau ...,1,2020-07-20 13:50:49
14995,albi store,Aku daftar layanan NYALA kenapa Jadi TANDA 360...,3,2020-07-20 10:03:06
14996,Mahasa Swt,Saya baru buka rekening di OCBC NISP Komentar ...,5,2020-07-20 02:47:32
14998,Erwin Pijat,Baru,5,2020-07-19 19:12:35
14999,Acep Mbef,Apk ni kacau banget. Sering update bukannya ta...,1,2020-07-19 16:16:57

17. Menampilkan Distribusi Rating

In [21]:
df["Rating"].value_counts()

Rating
1    5170
5    4420
2    1000
3     951
4     675
Name: count, dtype: int64